#dataSources:
#    dialect: org.hibernate.dialect.MySQLInnoDBDialect
#    driverClassName: com.mysql.jdbc.Driver
#    dbCreate: update
#    username: root
#    password: ""
#
#environments:
#  development:
#    dataSource:
#      dbCreate: update
#      #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#      url: jdbc:mysql://localhost/grailsapi
